# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04073aa3280bc97f33b1270be934012c8cc4db04926cccd3f57634100cbd68b3ab2fc0ec0cfd64630c963911542eeb2e068edac1dab62c64006881f1c5ed40e8

test:
  secret_key_base: d8dce4bf38f2afbab7fcf7903ab4b2bcbc9c4821163b5efbb28f3c32f762243a5db85f18c7bf5a887ca959b481cf3fc145e2e6703786b7b01b0742d645f554c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
